clc; close all;
DataDir = 'obs_000000.ply';
cloud_mov = pcread(DataDir);
DataDir = 'obs_000002.ply';
cloud_ref = pcread(DataDir);
params = genParamsFun(cloud_mov.Location', cloud_ref.Location', ...
    'mov_normal', cloud_mov.Normal', 'ref_normal', cloud_ref.Normal', ...
    'mode', 'point2point', ...
    'optimize', 'irls', ...
    'Hb_point2plane', 1, ... % if Hb_point2plane is set to be 1, Lie-algbra will be used. 
    'is_show', 1, 'verbose', 1);
MiNoMFun(params);