clc; close all;
DataDir = 'data/raw_000802.pcd';
cloud_mov = pcread(DataDir);
cloud_mov = pcdownsample(cloud_mov, 'random', 0.1); 
DataDir = 'data/raw_000804.pcd';
cloud_ref = pcread(DataDir);
params = genParamsFun(cloud_mov.Location', cloud_ref.Location', ...
    'ref_normal', cloud_ref.Normal', ...
    'P', [1.0 2.0], ...
    'mode', 'point2plane', ...
    'Tf0', eye(4), ...
    'is_show', 1, ...
    'verbose', 1 );
[rstR, rstT] = MiNoMFun(params);
